WEBDOM-391: Implement https://github.com/digipolisgent/symfony_bundle_domainator9k-core/pull/8
digipolisgent/symfony_bundle_domainator9k-citype-jenkins pull request #5
Opened 2018-06-07 13:57 UTC by Jelle-S

Implement https://github.com/digipolisgent/symfony_bundle_domainator9k-core/pull/8.

2018-06-11 12:13 UTC, matthijs-va requested changes

2018-06-11 12:13 UTC, matthijs-va commented on Provisioner/BuildProvisioner.php
> +                return;
Remove the setFailed() call and trow a LoggedException.

2018-06-11 12:13 UTC, matthijs-va commented on Provisioner/DestroyProvisioner.php
> +                return;
Remove the setFailed() call and trow a LoggedException.

2018-06-11 12:13 UTC, matthijs-va commented on Provisioner/DestroyProvisioner.php
> +                return;
Use a throw of the LoggedException.

2018-06-11 12:15 UTC, daften approved these changes

2018-06-12 14:05 UTC, matthijs-va approved these changes

2018-06-12 14:49 UTC, merged